### ISSUE TITLE
Add any License

### ISSUE THREAD

**Issue by Alexiscomete** [victorbnl/lavonic-cards-generator#1]
Salut ! Bon c'est un peu rapide comme ouverture d'issue (désolé) mais il faut savoir que Darki souhaite actuellement améliorer la génération de cartes et faire un site internet pour les Contrées Magmatiques. Or il aimerai bien pouvoir réutiliser une partie de ton code ou faire des pull request etc ... (si il retrouve son mot de passe github :octocat: ). Donc j'aimerai pouvoir lui expliquer ce qu'il peut faire avec ton code mais vu qu'il n'y a pas encore de License pour le moment il ne peut rien faire (bon en même temps le repo a été créé aujourd'hui).
Il s'intéresse de plus en plus au dev mais là il utilise un site internet de génération de sites internet.

**Comment by marie-bnl** [comment]
Pas de soucis ! Au contraire, j'apprécie les retours divers sur mes projets et te remercie pour cette remarque tout à fait pertinente
